### ISSUE TITLE
Day selection stops working when re-selecting weekly option in custom schedule

### ISSUE THREAD

**Issue by rachdaup93** [gregschmit/recurring_select#121]
There is an issue that happens when creating a custom weekly schedule. The days of the week are not selectable if you initially select weekly, then switch to another frequency, then reselect weekly.

Steps:
1. Select `Custom schedule ...` in the recurring rule drop-down.
2. Choose `Weekly` for the frequency
3. Change from `Weekly` to any other frequency (i.e. `Daily`)
4. Change back to `Weekly` frequency

The days of the week will not highlight when being selected.

**Comment by glaszig** [comment]
i came across this issue in my fork and fixed it. see #166.

`Gemfile`:

```rb
gem "recurring_select", github: "glaszig/recurring_select", branch: "modernization"
```
