### ISSUE TITLE
no pop up rails 7

### ISSUE THREAD

**Issue by AnabalonJT** [gregschmit/recurring_select#153]
Hey, I'm trying to use recurring_select in my rails 7 calendar app, but when I'm adding it in the  form, It doesn't show up the modal, there is no pop up when I try to create a customize recurring for my events in the calendar. The javascript isn't working.
Here is my code

gemfile
`gem "recurring_select", github: "/mb52089/recurring_select"`

_form.html.erb
`<%= form.select_recurring :recurring, nil, allow_blank: true%>`

importmap.rb
`pin "recurring_select", to: "https://cdn.jsdelivr.net/npm/recurring-select@0.1.0/"`

application.js
`import "recurring_select"`

application.scss
`@import "recurring_select";`

Can someone help me pls!

**Comment by garethfr** [comment]
I solvec this by adding the recurring_select path to the sass command in package.json - I'm using cssbundling-rails

` "build:css": "sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules --load-path=\"$(bundle show 'recurring_select')/app/assets/stylesheets\""`

**Comment by migu0** [comment]
Same here, couldn't get it working in Rails 7. Not using Webpacker, does anyone have any suggestions on how to use this?

**Comment by butzhang** [comment]
Same here. It doesn't work. Also who will use webpacker in rails 7? 🤣

**Comment by SansNumbers** [comment]
Hi guys! I've found my own way how to make it work on rails 7.

Gemfile
`gem "recurring_select", github: "gregschmit/recurring_select", branch: "master"`
_form.html.erb
`<%= form.select_recurring :recurring, nil, allow_blank: true%>`
application.js
`import './recurring_select'`
application.scss
`@import "recurring_select/recurring_select";`
And remember to install jQuery if you didn't do it yet.

Also i've added 4 files.
2 converted files from coffeescript to default javascript in
`app/javascript/recurring_select/index.js` and `app/javascript/recurring_select/recurring_select_dialog.js`
[Here is a link to download](https://www.jsdelivr.com/package/npm/recurring-select?path=dist)
And 2 scss files in
`app/assets/stylesheets/recurring_select/utilities.scss` and `app/assets/stylesheets/recurring_select/recurring_select.scss`.
[Here is a link to download](https://github.com/gregschmit/recurring_select/tree/master/app/assets/stylesheets)
Remember to check if they are connected in application files!
Afterwards, you should move from `index.js` file first method that invokes recurring select dialog to your custom stimulus controller.
Code in controller should be looking something like this:
```
  $(document).on('focus', '.recurring_select', function () {
    $(this).recurring_select('set_initial_values')
  })
  $(document).on('change', '.recurring_select', function () {
    $(this).recurring_select('changed')
  })
```
Let me know if it works or you have any comments on this :)

**Comment by spacerobotTR** [comment]
I am trying to get your method working but it is still not opening the modal. Do you have a full example app I can look at?

**Comment by tubsandcans** [comment]
I'm not sure why this was closed, as the only thing close to a solution (and a very inelegant one at that) involves a fork of this repo
