### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by gregschmit** [gregschmit/recurring_select#154]
I noticed the last commit to `master` was in August 2020, and there is a PR that would fix an issue I'm having in Rails 7 that hasn't been merged yet (https://github.com/GetJobber/recurring_select/pull/152) -- is this project abandoned? In any case, I volunteer to assist as a maintainer, if you're open to that.

**Comment by saturnflyer** [comment]
@gregschmit congrats on the maintainer-ship. Are you currently working on these issues?

**Comment by gregschmit** [comment]
Yes, i'm currently working on making sure the project works on Rails 7, then I want to look at the PRs that expand functionality. I took a look at `ice_cube_select`, and I really like what you've done there to remove coffeescript dependencies and stuff like that, so hopefully soon I can move towards including those great changes.
