### ISSUE TITLE
Working way to install for rails 7?

### ISSUE THREAD

**Issue by spacerobotTR** [gregschmit/recurring_select#158]
I have been struggling trying top get this installed and working with rails 7. Not sure if this gem is being worked on still, but was wondering if anyone could list the steps they have taken? I tried the methods listed in #153  and am getting errors on loading the javascript stating:

`script: Expected a JavaScript module script but the server responded with a MIME type of "text/coffeescript". Strict MIME type checking is enforced for module scripts per HTML spec.`

**Comment by spacerobotTR** [comment]
Wow i got it working. What I did was add this to importmap.rb

`pin_all_from "app/javascript/recurring-select", under: "recurring-select"`

Added the javascript files from #153 at the bottom under app/javascript/recurring-select. I had to change the jquery reference at the top of recurring_select_dialogue.js:

Old:

```
var $, RecurringSelectDialog;

$ = require("jquery");
```

New:

```
var RecurringSelectDialog;

import $ from "jquery";
```

Then in application.js I added ` import "recurring-select"`. 

In application.tailwind.css I added `@import "recurring_select/recurring_select";` and oput the two files referenced in that location.

Seems to be working! I'll need to go through and tweak the styles to bring over to tailwind.

**Comment by ryanckulp** [comment]
jQuery loads a bit differently in my Rails 7 app, so i followed your same instructions:

* importmap.rb `pin_all_from "app/javascript/recurring-select", under: "recurring-select"`
* pasted 2 JS files inside new `app/javascript/recurring-select` directory
* pasted 2 CSS files inside new `app/stylesheets/recurring_select` directory

except inside the 2 JS files i replaced:

```
import $ from "jquery";
```

with:

```
var $ = jQuery;
```

thanks for sharing this!
