### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by lafeber** [gregschmit/recurring_select#161]
Hi! I noticed there are quite a few pull requests open for quite some time. Some of them quite trivial, such as translations. There's often no response. But @gregschmit did to a version bump two months ago...

I'd love to help, e.g. to remove jQuery dependency. But I'd like my contribution not te be in vain.

**Comment by gregschmit** [comment]
I will absolutely merge new PRs. I am wary of merging the PRs that are vey old as newer changes may have rendered them no longer correct (even in the cases where there are no conflicts). I am also wary about translations, as I do not really think it's wise to adopt the maintenance burden of supporting foreign languages in this project. Unless I see the community commenting on the PRs saying "we neeed this, please merge!!", i'm not going to merge them. If however there is enough community support, then I'm happy to merge them.

New PRs I will consider much more strongly and I would give significantly more attention.

I initially adopted this repo to make it work with Rails 7, but there are many things I'd like to do, such as remove coffeescript, and I've even been looking at the most popular fork of this repo which is`ice_cube_select` by @saturnflyer and considered merging most of those commits into this project.

To your question: your effort would absolutely not be in vain and I would happily merge PRs that are known to be good. If you want to tag me in PRs you think ought to be merged, that would signal to me that users of this project want those features.
