### ISSUE TITLE
Error undefined method `=~' for 1:Integer (NoMethodError)

### ISSUE THREAD

**Issue by adriangs1996** [gregschmit/recurring_select#163]
Environment: 
 * Rails 7.0.4.3
 * recurring_select 3.0

Rule Hash:
`{:validations=>{:day_of_week=>{1=>[1, 3], 5=>[2, 4]}}, :rule_type=>"IceCube::MonthlyRule", :interval=>1}`

```ruby
hash = {:validations=>{:day_of_week=>{1=>[1, 3], 5=>[2, 4]}}, :rule_type=>"IceCube::MonthlyRule", :interval=>1}
RecurringSelect.is_valid_rule? hash
=> true

RecurringSelect.dirty_hash_to_rule hash
/Users/adriangonzalez/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/recurring_select-3.0.1/lib/recurring_select.rb:62:in `filter_params': undefined method `=~' for 1:Integer (NoMethodError)
```

I found that the offending line is line 62 of recurring_select.rb:

```ruby
if params[:validations][:day_of_week].length > 0 and not params[:validations][:day_of_week].keys.first =~ /\d/
```

It would be possible to coerce the first operator of the matching operation to be a String? If I call to_s the bug is solved for this case

```ruby
if params[:validations][:day_of_week].length > 0 and not params[:validations][:day_of_week].keys.first.to_s =~ /\d/
```
Is possible to reproduce this issue with the recurring_select form field, going for a monthly frecuency and selecting day_of_weeks with the first and third monday, and then the second and fourth friday. (That would give you the hash above).

**Comment by gregschmit** [comment]
Yeah your fix looks very reasonable; I've added it. Thank you!
