### ISSUE TITLE
Heroku live demo app is erroring

### ISSUE THREAD

**Issue by mattgoldman** [gregschmit/recurring_select#27]
http://recurring-select-demo.herokuapp.com/

Getting the following boilerplate Heroku error:

```
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

**Comment by tubsandcans** [comment]
The Heroku app is non-existent?. http://recurring-select-demo.herokuapp.com: "There's nothing here, yet."
